In [ ]:
import pandas as pd
from get_img import get_img
import re
import random

In [ ]:
cities = pd.read_csv("data/othercities.csv")

In [ ]:
cities.head()

      City       long1       long2       lat1       lat2  num_tiles
0  Houston  -95.383906  -95.342306  29.766633  29.743192         30
1  Seattle -122.341736 -122.319350  47.625851  47.536030         50
2  Chicago  -87.687691  -87.617477  41.931628  41.810367         50
3  Atlanta  -84.419513  -84.355648  33.795891  33.736997         50

In [ ]:
# for each city, create a vector of random points
longs = []
lats = []
coords=[]

for i in range(cities.shape[0]):
    coord = []
    for j in range(cities.num_tiles[i]):
        long = random.uniform(cities.long1[i], cities.long2[i])
        lat = random.uniform(cities.lat2[i], cities.lat1[i])
        coord.append((lat, long))
    coords.append(coord)

In [ ]:
cities["coords"] = coords
cities.head()

,City,long1,long2,lat1,lat2,num_tiles,coords
0,Houston,-95.383906,-95.342306,29.766633,29.743192,30,"[(29.756313055993875, -95.36309394329216), (29..."
1,Seattle,-122.341736,-122.319350,47.625851,47.536030,50,"[(47.54506425132844, -122.33505338033636), (47..."
2,Chicago,-87.687691,-87.617477,41.931628,41.810367,50,"[(41.923318401950134, -87.64510873067961), (41..."
3,Atlanta,-84.419513,-84.355648,33.795891,33.736997,50,"[(33.74248614433411, -84.39286175450337), (33...."

In [ ]:
for i in range(cities.shape[0]): 
    print(cities.City[i], end="\n")
    for j in range(len(cities.coords[i])):
        print(j, end=' ')
        street = str(cities.coords[i][j][0])+"+"+str(cities.coords[i][j][1])
        get_img(center=street, filename="data/othercities/"+cities.City[i]+str(j), zoom=19, size="640x640", sc=2, fmt="png", maptype="satellite")

In [ ]:
street = str(cities.coords[i][j][0])+","+str(cities.coords[i][j][1])

street
# get_img(center=street, filename="data/othercities/"+cities.City[i]+str(j), zoom=19, size="640x640", sc=2, fmt="png", maptype="satellite")

'-95.471346,29.74846383163781'

In [ ]:
get_img(center=street, filename="data/othercities/"+cities.City[i]+str(j), zoom=19, size="640x640", sc=2, fmt="png", maptype="satellite")

In [ ]:
# ctid = ["data/nys/"+str(x) for x in nys.UniqueID]
ctid = ["data/phil/"+str(x) for x in phl.ctnum]

In [ ]:
# ctid[267:]
# nys.head()

In [ ]:
# st0 = [x.split("\n")[0].replace(".", "")+" "+x.split("\n")[1].replace(",", "") for x in nys.NewGeoreferencedColumn]

# street = ["+".join(x.split()) for x in st0]

# Philly
street = [str(x)+","+str(y) for x, y in zip(phl.PointX, phl.PointY)]

In [ ]:
street[0:10]

['40.04446078,-75.04194683',
 '39.98560638,-75.15892426',
 '39.95702675,-75.19660854',
 '39.94723298,-75.15848305',
 '40.03757852,-75.15210494',
 '40.03544526,-75.10355188',
 '39.96217124,-75.16433567',
 '39.95034356,-75.16520762',
 '39.95097849,-75.17932249',
 '39.96384471,-75.17472539']

In [ ]:
len(ctid)
# list(range(1, 3))

550

In [ ]:
for i in range(len(ctid)): 
    print(i, end=' ')
    get_img(center=street[i], filename=ctid[i], zoom=19, size="640x640", sc=2, fmt="png", maptype="satellite")